# Generated by Django 3.2.5 on 2021-07-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_url', models.TextField()),
                ('page_depth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.ImageField(upload_to='')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.content')),
            ],
        ),
        migrations.CreateModel(
            name='SubURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_url', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.content')),
                ('master_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.masterurl')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.content')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.content')),
            ],
        ),
    ]
